
# services:
#   db:
#     image: postgres:15
#     container_name: lakehouse_db
#     restart: always
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: lakehouse
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./data/postgres2:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U admin"]
#       interval: 5s
#       retries: 5
#       start_period: 10s

  # etl:
  #   build: ./etl
  #   container_name: airbnb_etl
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./:/data
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_NAME: lakehouse
  #     DB_USER: admin
  #     DB_PASSWORD: admin
  #     PYTHONUNBUFFERED: 1
  #   #command: ["python", "-u", "populate_db.py"]

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: airbnb-pgadmin
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - airbnb-net

version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: airbnb-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airbnb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airbnb-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: airbnb-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - airbnb-net

networks:
  airbnb-net:

volumes:
  pgdata:
